//
//  DMAC.swift
//  SwiftARMGeneratorCLI
//
//  Created by HALGEN on 05/21/2026.
//

import Foundation

struct DMACGenerator: PeripheralGenerator {
    let name = "DMAC"
    let subdirectory = "module"

    func supports(device: SVDDevice) -> Bool {
        dmacPeripheral(in: device) != nil
    }

    func generate(device: SVDDevice) -> [GeneratedCodeFile] {
        guard let peripheral = dmacPeripheral(in: device) else {
            return []
        }

        return [buildDMACFile(device: device, peripheral: peripheral, documentation: nil, documentationDirectory: nil)]
    }

    func generate(device: SVDDevice, documentation: ChipDocumentationLoader) -> [GeneratedCodeFile] {
        guard let peripheral = dmacPeripheral(in: device) else {
            return []
        }

        return [
            buildDMACFile(
                device: device,
                peripheral: peripheral,
                documentation: documentation,
                documentationDirectory: documentation.directory
            )
        ]
    }
}

// MARK: - Peripheral Detection

private func dmacPeripheral(in device: SVDDevice) -> SVDPeripheral? {
    device.peripherals.first { $0.name == "DMAC" || $0.groupName == "DMAC" }
}

// MARK: - File Builder

private func buildDMACFile(
    device: SVDDevice,
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?,
    documentationDirectory: URL?
) -> GeneratedCodeFile {
    let fileName = "DMAC.swift"
    let moduleName = device.generatedSwiftModuleName
    let baseName = "DMAC_BASE"
    let baseAddress = peripheral.baseAddress ?? 0
    let registers = peripheral.registers.map(dmacRegisterForGeneration)
    let fieldUsage = dmacFieldUsage(in: registers, peripheral: peripheral, documentation: documentation)
    let registerVariableNames = Set(registers.map { register in
        dmacRegisterData(for: register, peripheral: peripheral, documentation: documentation).variableName
    })

    var code = generatedFileHeader(
        fileName: fileName,
        moduleName: moduleName,
        description: "Generated by Swift ARM Generator from \(device.name)."
    )

    code += "@usableFromInline let \(baseName): UInt = \(hexLiteral(baseAddress, minimumDigits: 8))   // SAMD21 DMAC base address\n\n"

    code += """
    /// Direct Memory Access Controller.
    ///
    /// Provides the DMAC peripheral registers plus the SRAM descriptor layout used by
    /// BASEADDR and WRBADDR. Enable the DMAC clocks in PowerManager before touching
    /// these registers.
    struct DMAC {

    """

    code += generateDMACSupportingTypes(device: device, documentationDirectory: documentationDirectory)

    for register in registers {
        code += dmacRegisterSectionHeader(for: register)
        code += generateSVDRegister(
            register: register,
            baseName: baseName,
            indentation: 4,
            writeBehavior: dmacWriteBehavior(for: register),
            registerData: { register in
                dmacRegisterData(for: register, peripheral: peripheral, documentation: documentation)
            },
            bitfieldData: { field in
                dmacBitfieldData(
                    for: field,
                    register: register,
                    peripheral: peripheral,
                    fieldUsage: fieldUsage,
                    registerVariableNames: registerVariableNames,
                    documentation: documentation
                )
            }
        )
    }

    code += "}\n"

    return GeneratedCodeFile(fileName: fileName, content: code, subdirectory: "module")
}

// MARK: - Supporting Types

private func generateDMACSupportingTypes(device: SVDDevice, documentationDirectory: URL?) -> String {
    guard let documentationDirectory else {
        return ""
    }

    return BoilerplateTemplate.render(
        named: "DMACSupportingTypes.swift",
        documentationDirectory: documentationDirectory,
        substitutions: ["triggerCases": generateDMACTriggerSourceCases(device: device)]
    )
}

private func generateDMACTriggerSourceCases(device: SVDDevice) -> String {
    var code = ""

    for instance in dmacSERCOMInstances(in: device) {
        let receiveValue = UInt32(1 + instance.index * 2)
        let transmitValue = UInt32(2 + instance.index * 2)
        let lowerName = instance.name.lowercased()
        code += "        case \(lowerName)Receive = \(receiveValue)\n"
        code += "        case \(lowerName)Transmit = \(transmitValue)\n"
    }

    return code
}

private struct DMACSERCOMInstance {
    let name: String
    let index: Int
}

private func dmacSERCOMInstances(in device: SVDDevice) -> [DMACSERCOMInstance] {
    device.peripherals
        .compactMap { peripheral -> DMACSERCOMInstance? in
            guard peripheral.name.hasPrefix("SERCOM"),
                  let index = Int(peripheral.name.dropFirst("SERCOM".count)) else {
                return nil
            }

            return DMACSERCOMInstance(name: peripheral.name, index: index)
        }
        .sorted { $0.index < $1.index }
}

// MARK: - Register Generation Data

private func dmacRegisterForGeneration(_ register: SVDRegister) -> SVDRegister {
    guard register.fields.count == 1,
          let field = register.fields.first,
          field.bitOffset == 0,
          field.bitWidth == register.size else {
        return register
    }

    return SVDRegister(
        name: register.name,
        derivedFrom: register.derivedFrom,
        displayName: register.displayName,
        description: register.description,
        alternateGroup: register.alternateGroup,
        alternateRegister: register.alternateRegister,
        addressOffset: register.addressOffset,
        size: register.size,
        access: register.access,
        protection: register.protection,
        resetValue: register.resetValue,
        resetMask: register.resetMask,
        dim: register.dim,
        dimIncrement: register.dimIncrement,
        dimIndex: register.dimIndex,
        fields: []
    )
}

private func dmacRegisterSectionHeader(for register: SVDRegister) -> String {
    let offset = register.addressOffset.map { hexLiteral($0) } ?? "unknown"
    let size = register.size ?? 32
    let description = register.description ?? "Register"

    return "    // MARK: - \(register.name) - \(description) (Offset \(offset), \(size)-bit)\n\n"
}

private func dmacRegisterData(
    for register: SVDRegister,
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?
) -> SupplementalRegisterData {
    if let supplementalData = documentation?.supplementalData(for: register, peripheral: peripheral),
       supplementalData.isMissing == false {
        return supplementalData
    }

    return SupplementalRegisterData(
        variableName: swiftMemberIdentifier(from: register.displayName ?? register.name),
        valueType: "UInt32",
        defaultValue: "",
        documentation: "",
        access: "",
        isMissing: true
    )
}

private func dmacBitfieldData(
    for field: SVDField,
    register: SVDRegister,
    peripheral: SVDPeripheral,
    fieldUsage: [String: Int],
    registerVariableNames: Set<String>,
    documentation: ChipDocumentationLoader?
) -> SupplementalBitfieldData {
    if let supplementalData = documentation?.supplementalData(for: field, register: register, peripheral: peripheral),
       supplementalData.isMissing == false {
        return supplementalData
    }

    return SupplementalBitfieldData(
        variableName: dmacBitfieldVariableName(
            for: field,
            register: register,
            fieldUsage: fieldUsage,
            registerVariableNames: registerVariableNames,
            peripheral: peripheral,
            documentation: documentation
        ),
        valueType: "",
        defaultValue: "",
        documentation: "",
        access: dmacAccess(from: field.access ?? register.access ?? "read-write"),
        isMissing: true
    )
}

private func dmacWriteBehavior(for register: SVDRegister) -> SVDRegisterWriteBehavior {
    switch register.name {
    case "SWTRIGCTRL", "CHINTENCLR", "CHINTENSET", "CHINTFLAG":
        return .writeOneToClear
    default:
        return .normal
    }
}

private func dmacAccess(from access: String) -> Access {
    switch access.lowercased() {
    case "read-only", "r":
        return .read
    case "write-only", "w":
        return .write
    default:
        return .readWrite
    }
}

private func dmacBitfieldVariableName(
    for field: SVDField,
    register: SVDRegister,
    fieldUsage: [String: Int],
    registerVariableNames: Set<String>,
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?
) -> String {
    let fieldName = dmacBitfieldBaseName(
        for: field,
        register: register,
        peripheral: peripheral,
        documentation: documentation
    )
    let registerName = dmacRegisterData(for: register, peripheral: peripheral, documentation: documentation).variableName
    let needsRegisterPrefix = (fieldUsage[fieldName] ?? 0) > 1
        || fieldName == registerName
        || registerVariableNames.contains(fieldName)

    guard needsRegisterPrefix else {
        return fieldName
    }

    return "\(registerName)\(dmacUpperCamelIdentifier(from: fieldName))"
}

private func dmacFieldUsage(
    in registers: [SVDRegister],
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?
) -> [String: Int] {
    registers.reduce(into: [:]) { counts, register in
        for field in register.fields {
            let fieldName = dmacBitfieldBaseName(
                for: field,
                register: register,
                peripheral: peripheral,
                documentation: documentation
            )
            counts[fieldName, default: 0] += 1
        }
    }
}

private func dmacBitfieldBaseName(
    for field: SVDField,
    register: SVDRegister,
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?
) -> String {
    if let supplementalData = documentation?.supplementalData(for: field, register: register, peripheral: peripheral),
       supplementalData.isMissing == false,
       supplementalData.variableName.isEmpty == false {
        return supplementalData.variableName
    }

    return swiftMemberIdentifier(from: field.name)
}

private func dmacUpperCamelIdentifier(from memberName: String) -> String {
    guard let first = memberName.first else {
        return memberName
    }

    return String(first).uppercased() + memberName.dropFirst()
}
