//
//  GenericClockController.swift
//  SwiftARMGeneratorCLI
//
//  Created by HALGEN on 05/05/2026.
//

import Foundation

struct GenericClockControllerGenerator: PeripheralGenerator {
    let name = "GenericClockController"
    let subdirectory = "module"

    func supports(device: SVDDevice) -> Bool {
        guard let peripheral = gclkPeripheral(in: device) else {
            return false
        }

        return gclkHasRequiredRegisters(peripheral)
    }

    func generate(device: SVDDevice) -> [GeneratedCodeFile] {
        guard let peripheral = gclkPeripheral(in: device), gclkHasRequiredRegisters(peripheral) else {
            return []
        }
        return [buildGCLKFile(device: device, peripheral: peripheral, documentation: nil)]
    }

    func generate(device: SVDDevice, documentation: ChipDocumentationLoader) -> [GeneratedCodeFile] {
        guard let peripheral = gclkPeripheral(in: device), gclkHasRequiredRegisters(peripheral) else {
            return []
        }
        return [buildGCLKFile(device: device, peripheral: peripheral, documentation: documentation)]
    }
}

// MARK: - Peripheral Detection

private func gclkPeripheral(in device: SVDDevice) -> SVDPeripheral? {
    device.peripherals.first { $0.name == "GCLK" || $0.groupName == "GCLK" }
}

private let gclkRequiredRegisterNames: Set<String> = ["CTRL", "STATUS", "CLKCTRL", "GENCTRL", "GENDIV"]

private func gclkHasRequiredRegisters(_ peripheral: SVDPeripheral) -> Bool {
    gclkRequiredRegisterNames.allSatisfy { name in
        peripheral.registers.contains { $0.name == name }
    }
}

// MARK: - File Builder

private func buildGCLKFile(
    device: SVDDevice,
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?
) -> GeneratedCodeFile {
    let fileName = "GenericClockController.swift"
    let moduleName = device.generatedSwiftModuleName
    let baseName = "GCLK_BASE"
    let baseAddress = peripheral.baseAddress ?? 0
    let registers = peripheral.registers

    var code = generatedFileHeader(
        fileName: fileName,
        moduleName: moduleName,
        description: "Generated by Swift ARM Generator from \(device.name)."
    )

    code += "@usableFromInline let \(baseName): UInt = \(hexLiteral(baseAddress, minimumDigits: 8))   // SAMD21 datasheet §15.8\n\n"

    code += """
    /// Generic Clock Controller
    ///
    /// The Generic Clock Controller (GCLK) manages the distribution of clocks from various sources
    /// to the peripherals on the SAMD21. It consists of Generic Clock Generators (0–8), each of
    /// which can be independently configured with a clock source and division factor. Each generator's
    /// output can then be routed to one or more peripheral clock inputs via the CLKCTRL register.
    ///
    /// Typical setup sequence:
    ///   1. Configure a Generator: write GENDIV (division factor), then write GENCTRL (source + enable).
    ///   2. Wait for SYNCBUSY to clear.
    ///   3. Route the Generator to a peripheral: write CLKCTRL (generator + peripheral ID + enable).
    ///
    /// See SAMD21 datasheet Section 15.
    struct GenericClockController {

    """

    code += generateEnums(peripheral: peripheral, documentation: documentation)

    for register in registers where gclkRequiredRegisterNames.contains(register.name) {
        code += gclkRegisterSectionHeader(for: register)
        code += generateSVDRegister(
            register: register,
            baseName: baseName,
            indentation: 4,
            registerData: { register in
                gclkRegisterData(for: register, peripheral: peripheral, documentation: documentation)
            },
            bitfieldData: { field in
                gclkBitfieldData(for: field, register: register, peripheral: peripheral, documentation: documentation)
            }
        )
    }

    code += gclkRouteGeneratorHelper()
    code += "}\n"

    return GeneratedCodeFile(fileName: fileName, content: code, subdirectory: "module")
}

// MARK: - Enum Generation

private func generateEnums(peripheral: SVDPeripheral, documentation: ChipDocumentationLoader?) -> String {
    var code = "    // MARK: - Supporting Enums\n\n"
    code += generateGeneratorEnum(peripheral: peripheral, documentation: documentation)
    code += generateClockSourceEnum(peripheral: peripheral, documentation: documentation)
    code += generatePeripheralClockIDEnum(peripheral: peripheral, documentation: documentation)
    code += generateDivideSelectionEnum()
    return code
}

private func generateGeneratorEnum(peripheral: SVDPeripheral, documentation: ChipDocumentationLoader?) -> String {
    var code = ""
    code += "    /// Generic Clock Generator selection.\n"
    code += "    /// The SAMD21 provides nine independent Generic Clock Generators (0 through 8).\n"
    code += "    /// Generator 0 is the main clock generator and has a 16-bit division register;\n"
    code += "    /// Generators 1–8 have 8-bit division registers.\n"
    code += "    enum Generator: UInt32 {\n"

    if let context = gclkEnumContext(fieldName: "GEN", registerName: "CLKCTRL", in: peripheral) {
        for value in sortedEnumValues(context.field) {
            guard let rawValue = value.value else {
                continue
            }

            let swiftName = gclkEnumCaseName(for: value, context: context, documentation: documentation)
            code += "        case \(swiftName) = \(rawValue)\n"
        }
    }

    code += "    }\n\n"
    return code
}

private func generateClockSourceEnum(peripheral: SVDPeripheral, documentation: ChipDocumentationLoader?) -> String {
    var code = ""
    code += "    /// Clock source selection for a Generic Clock Generator (GENCTRL.SRC).\n"
    code += "    /// See SAMD21 datasheet Section 15.8.4 and Table 15-1.\n"
    code += "    enum ClockSource: UInt32 {\n"

    if let context = gclkEnumContext(fieldName: "SRC", registerName: "GENCTRL", in: peripheral) {
        for value in sortedEnumValues(context.field) {
            guard let rawValue = value.value else {
                continue
            }

            let swiftName = gclkEnumCaseName(for: value, context: context, documentation: documentation)
            let description = gclkEnumCaseDocumentation(for: value, context: context, documentation: documentation)
            code += "        /// \(description)\n"
            code += "        case \(swiftName) = \(hexLiteral(rawValue))\n"
        }
    }

    code += "    }\n\n"
    return code
}

private func generatePeripheralClockIDEnum(peripheral: SVDPeripheral, documentation: ChipDocumentationLoader?) -> String {
    var code = ""
    code += "    /// Peripheral clock input selection for CLKCTRL.ID.\n"
    code += "    /// Identifies which peripheral's generic clock input to configure.\n"
    code += "    /// See SAMD21 datasheet Section 15.8.3 and Table 15-2.\n"
    code += "    enum PeripheralClockID: UInt32 {\n"

    if let context = gclkEnumContext(fieldName: "ID", registerName: "CLKCTRL", in: peripheral) {
        for value in sortedEnumValues(context.field) {
            guard let rawValue = value.value else {
                continue
            }

            let swiftName = gclkEnumCaseName(for: value, context: context, documentation: documentation)
            let description = gclkEnumCaseDocumentation(for: value, context: context, documentation: documentation)
            code += "        /// \(description)\n"
            code += "        case \(swiftName) = \(hexLiteral(rawValue))\n"
        }
    }

    code += "    }\n\n"
    return code
}

private func generateDivideSelectionEnum() -> String {
    return """
        /// Division mode for a Generic Clock Generator (GENCTRL.DIVSEL).
        /// Controls how the GENDIV.DIV value is interpreted.
        /// See SAMD21 datasheet Section 15.8.4.
        enum DivideSelection: UInt32 {
            /// Linear division: f_out = f_src / (DIV+1), or f_src if DIV = 0.
            case linear = 0
            /// Power-of-two division: f_out = f_src / 2^(DIV+1).
            case powerOfTwo = 1
        }


    """
}

// MARK: - Register Generation Data

private func gclkRegisterSectionHeader(for register: SVDRegister) -> String {
    switch register.name {
    case "CTRL":
        return """
        // MARK: - CTRL – Control Register (Offset 0x00, 8-bit)
        //
        // CTRL, STATUS, and CLKCTRL share one 32-bit-aligned word at GCLK_BASE.
        // Little-endian 32-bit layout at GCLK_BASE:
        //   Bits  [7:0]  = CTRL    (offset 0x00, R/W 8-bit)
        //   Bits [15:8]  = STATUS  (offset 0x01, R   8-bit)
        //   Bits [31:16] = CLKCTRL (offset 0x02, R/W 16-bit)
        //
        // Each register property below performs a 32-bit read-modify-write so that
        // it only affects its own field and leaves the others intact.


    """
    case "GENCTRL":
        return "    // MARK: - GENCTRL – Generic Clock Generator Control (Offset 0x04, 32-bit)\n\n"
    case "GENDIV":
        return "    // MARK: - GENDIV – Generic Clock Generator Division (Offset 0x08, 32-bit)\n\n"
    default:
        return ""
    }
}

private func gclkRegisterData(
    for register: SVDRegister,
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?
) -> SupplementalRegisterData {
    if let documentation {
        return documentation.supplementalData(for: register, peripheral: peripheral)
    }

    return SupplementalRegisterData(
        variableName: swiftMemberIdentifier(from: register.displayName ?? register.name),
        valueType: "UInt32",
        defaultValue: "",
        documentation: "",
        access: register.access ?? "read-write",
        isMissing: true
    )
}

private func gclkBitfieldData(
    for field: SVDField,
    register: SVDRegister,
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?
) -> SupplementalBitfieldData {
    if let documentation {
        return documentation.supplementalData(for: field, register: register, peripheral: peripheral)
    }

    return SupplementalBitfieldData(
        variableName: swiftMemberIdentifier(from: field.name),
        valueType: field.bitWidth == 1 ? "Bool" : "UInt32",
        defaultValue: "",
        documentation: "",
        access: gclkAccess(from: field.access ?? "read-write"),
        isMissing: true
    )
}

private func gclkAccess(from access: String) -> Access {
    switch access.lowercased() {
    case "read-only", "r":
        return .read
    case "write-only", "w":
        return .write
    default:
        return .readWrite
    }
}

// MARK: - SVD Helpers

private struct GCLKEnumContext {
    let peripheral: SVDPeripheral
    let register: SVDRegister
    let field: SVDField
}

private func gclkEnumContext(fieldName: String, registerName: String, in peripheral: SVDPeripheral) -> GCLKEnumContext? {
    guard let register = peripheral.registers.first(where: { $0.name == registerName }) else {
        return nil
    }
    guard let field = register.fields.first(where: { $0.name == fieldName }) else {
        return nil
    }

    return GCLKEnumContext(peripheral: peripheral, register: register, field: field)
}

private func sortedEnumValues(_ field: SVDField) -> [SVDEnumeratedValue] {
    (field.enumeratedValues.first?.values ?? []).sorted { lhs, rhs in
        (lhs.value ?? 0) < (rhs.value ?? 0)
    }
}

private func gclkEnumCaseName(
    for value: SVDEnumeratedValue,
    context: GCLKEnumContext,
    documentation: ChipDocumentationLoader?
) -> String {
    if let caseName = documentation?
        .supplementalData(for: value, field: context.field, register: context.register, peripheral: context.peripheral)?
        .caseName,
        caseName.isEmpty == false {
        return caseName
    }

    return swiftMemberIdentifier(from: value.name)
}

private func gclkEnumCaseDocumentation(
    for value: SVDEnumeratedValue,
    context: GCLKEnumContext,
    documentation: ChipDocumentationLoader?
) -> String {
    if let enumDocs = documentation?
        .supplementalData(for: value, field: context.field, register: context.register, peripheral: context.peripheral)?
        .documentation,
        enumDocs.isEmpty == false {
        return enumDocs
    }

    return value.description ?? value.name
}

// MARK: - Route Generator Helper

private func gclkRouteGeneratorHelper() -> String {
    """
        // MARK: - Helper

        /// Route a Generic Clock Generator to a peripheral clock input and wait for synchronization.
        ///
        /// This writes CLKCTRL with the specified peripheral clock ID, generator selection,
        /// and clock enable via a volatile 16-bit store, then waits for CLKCTRL
        /// synchronization to complete.
        ///
        /// - Parameters:
        ///   - id: The peripheral clock input to configure.
        ///   - generator: The Generic Clock Generator to route to the peripheral.
        ///   - enable: Whether to enable the clock. Defaults to `true`.
        @inlinable @inline(__always)
        static func routeGenerator(id: PeripheralClockID, generator: Generator, enable: Bool = true) {
            let genVal = generator.rawValue << 8
            let enableVal: UInt32 = enable ? (UInt32(1) << 14) : 0
            let value = id.rawValue | genVal | enableVal
            _volatileRegisterWriteUInt16(GCLK_BASE + 0x02, UInt16(value & 0xFFFF))
            while synchronizationBusy {}
        }

    """
}
