//
//  GPIO.swift
//  SwiftARMGeneratorCLI
//
//  Created by Friso De Backer on 24/04/2026.
//

import Foundation

struct GPIOGenerator: PeripheralGenerator {
    let name: String = "GPIO"
    let subdirectory: String = "module"

    func supports(device: SVDDevice) -> Bool {
        portPeripheral(in: device) != nil
    }

    func generate(device: SVDDevice) -> [GeneratedCodeFile] {
        guard let port = portPeripheral(in: device) else {
            return []
        }

        return [buildGPIO(device: device, peripheral: port, subdirectory: subdirectory)]
    }

    func generate(device: SVDDevice, documentation: ChipDocumentationLoader) -> [GeneratedCodeFile] {
        guard let port = portPeripheral(in: device) else {
            return []
        }

        return [buildGPIO(device: device, peripheral: port, subdirectory: subdirectory, documentation: documentation)]
    }
}

private func buildGPIO(device: SVDDevice, peripheral: SVDPeripheral, subdirectory: String, documentation: ChipDocumentationLoader? = nil) -> GeneratedCodeFile {
    let fileName = "GPIO.swift"
    let moduleName = device.generatedSwiftModuleName
    let groupCount = portGroupCount(in: peripheral)
    let groupStride = portGroupStride(in: peripheral)
    let baseAddress = peripheral.baseAddress ?? 0
    let registers = gpioRegisters(in: peripheral)

    var code = generatedFileHeader(
        fileName: fileName,
        moduleName: moduleName,
        description: "Generated by Swift ARM Generator from \(device.name)."
    )

    for groupIndex in 0..<groupCount {
        let portName = portTypeName(for: groupIndex)
        let groupBase = baseAddress + UInt64(groupIndex) * groupStride

        code += "@usableFromInline let \(portName)_BASE: UInt = \(hexLiteral(groupBase, minimumDigits: 8))\n"
    }

    code += """

    struct GPIO {
        private init() {}

    """

    for groupIndex in 0..<groupCount {
        code += buildPortGroup(
            name: portTypeName(for: groupIndex),
            groupIndex: groupIndex,
            registers: registers,
            documentation: documentation
        )
    }

    code += buildPads(groupCount: groupCount)
    code += "}\n"

    return GeneratedCodeFile(fileName: fileName, content: code, subdirectory: subdirectory)
}

private func portPeripheral(in device: SVDDevice) -> SVDPeripheral? {
    device.peripherals.first { peripheral in
        peripheral.name == "PORT" || peripheral.groupName == "PORT"
    }
}

private func gpioRegisters(in peripheral: SVDPeripheral) -> [SVDRegister] {
    peripheral.registers.filter(isGPIORegister)
}

private func isGPIORegister(_ register: SVDRegister) -> Bool {
    [
        "DIR",
        "DIRCLR",
        "DIRSET",
        "DIRTGL",
        "OUT",
        "OUTCLR",
        "OUTSET",
        "OUTTGL",
        "IN",
        "CTRL",
        "WRCONFIG",
        "PMUX0",
        "PINCFG0"
    ].contains(normalizedRegisterName(register.name))
}

private func portGroupCount(in peripheral: SVDPeripheral) -> Int {
    let counts = peripheral.registers.compactMap { register -> Int? in
        guard isPortGroupRegister(register) else {
            return nil
        }

        return register.dim
    }

    return max(counts.max() ?? 1, 1)
}

private func portGroupStride(in peripheral: SVDPeripheral) -> UInt64 {
    peripheral.registers.first(where: isPortGroupRegister)?.dimIncrement ?? 0x80
}

private func isPortGroupRegister(_ register: SVDRegister) -> Bool {
    let name = normalizedRegisterName(register.name)

    return [
        "DIR",
        "DIRCLR",
        "DIRSET",
        "DIRTGL",
        "OUT",
        "OUTCLR",
        "OUTSET",
        "OUTTGL",
        "IN",
        "CTRL",
        "WRCONFIG"
    ].contains(name)
}

private func buildPortGroup(name portName: String, groupIndex: Int, registers: [SVDRegister], documentation: ChipDocumentationLoader?) -> String {
    var code = """
        struct \(portName): AtomicPort {
            private init() {}

    """

    for register in registers {
        code += buildPortRegister(
            register: register,
            portName: portName,
            groupIndex: groupIndex,
            documentation: documentation
        )
    }

    code += """
        }

    """

    return code
}

private func buildPortRegister(register: SVDRegister, portName: String, groupIndex: Int, documentation: ChipDocumentationLoader?) -> String {
    if let dim = register.dim, dim > 1, register.dimIncrement == 1 {
        return (0..<dim)
            .map { index in
                buildRegisterProperty(
                    register: register,
                    portName: portName,
                    groupIndex: groupIndex,
                    elementIndex: index,
                    documentation: documentation
                )
            }
            .joined()
    }

    return buildRegisterProperty(
        register: register,
        portName: portName,
        groupIndex: groupIndex,
        documentation: documentation
    )
}

private func buildRegisterProperty(
    register: SVDRegister,
    portName: String,
    groupIndex: Int,
    elementIndex: Int? = nil,
    documentation: ChipDocumentationLoader? = nil
) -> String {
    guard let addressOffset = register.addressOffset else {
        return ""
    }

    let registerName = displayRegisterName(register.name, elementIndex: elementIndex)
    let suppData = documentation?.supplementalData(for: register)
    let variableName = suppData?.variableName ?? gpioRegisterVariableName(for: register, elementIndex: elementIndex) ?? ""
    guard variableName.isEmpty == false else {
        return ""
    }

    let offset = addressOffset + UInt64(elementIndex ?? 0) * (register.dimIncrement ?? 0)
    let addressExpression = registerAddressExpression(baseName: "\(portName)_BASE", offset: offset)
    let access = suppData?.access ?? register.access ?? "read-write"
    let isReadOnly = access == "read-only"
    let registerDocumentation: String
    if let suppDocs = suppData?.documentation, suppDocs.isEmpty == false {
        registerDocumentation = makeDocumentationComment(body: suppDocs)
    } else {
        let description = register.description ?? registerName
        registerDocumentation = makeRegisterDocumentation(registerName: registerName, description: description, register: register)
    }

    return """

            \(registerDocumentation)
            @inline(__always)
            static var \(variableName): UInt32 {
    \(buildGetter(addressExpression: addressExpression, offset: offset, registerSize: register.size ?? 32))
    \(isReadOnly ? "" : buildSetter(addressExpression: addressExpression, offset: offset, registerSize: register.size ?? 32))
            }

    """
}

private func buildGetter(addressExpression: String, offset: UInt64, registerSize: Int) -> String {
    svdIndent(
        buildSVDRegisterGetter(
            addressExpression: addressExpression,
            offset: offset,
            registerSize: registerSize
        ),
        by: 12
    )
}

private func buildSetter(addressExpression: String, offset: UInt64, registerSize: Int) -> String {
    svdIndent(
        buildSVDRegisterSetter(
            addressExpression: addressExpression,
            offset: offset,
            registerSize: registerSize,
            writeBehavior: .normal
        ),
        by: 12
    )
}

private func registerAddressExpression(baseName: String, offset: UInt64) -> String {
    svdRegisterAddressExpression(baseName: baseName, offset: offset)
}

private func makeRegisterDocumentation(registerName: String, description: String, register: SVDRegister) -> String {
    var lines = [
        "/// \(description) - \(registerName)"
    ]

    let normalizedRegister = normalizedRegisterName(register.name)

    for field in register.fields {
        guard let fieldDescription = field.description else {
            continue
        }

        let normalizedField = normalizedRegisterName(field.name)
        if register.fields.count == 1 && normalizedField == normalizedRegister {
            continue
        }

        lines.append("/// \(field.name): \(fieldDescription)")
    }

    return lines.joined(separator: "\n        ")
}

private func buildPads(groupCount: Int) -> String {
    var code = ""

    for groupIndex in 0..<groupCount {
        let portName = portTypeName(for: groupIndex)
        let padPrefix = padPrefixName(for: groupIndex)

        code += """

        /// \(portName)

    """

        for bit in 0..<32 {
            code += "    typealias \(padPrefix)\(String(format: "%02d", bit)) = DigitalPin<\(portName), Bit\(bit)>\n"
        }
    }

    return code
}

private func portTypeName(for index: Int) -> String {
    "PORT\(portLetter(for: index))"
}

private func padPrefixName(for index: Int) -> String {
    "P\(portLetter(for: index))"
}

private func portLetter(for index: Int) -> String {
    String(UnicodeScalar(65 + index)!)
}

private func displayRegisterName(_ rawName: String, elementIndex: Int?) -> String {
    let normalizedName = normalizedRegisterName(rawName)

    if let elementIndex, normalizedName == "PMUX0" {
        return "PMUX\(elementIndex)"
    }

    if let elementIndex, normalizedName == "PINCFG0" {
        return "PINCFG\(elementIndex)"
    }

    return normalizedName
}

private func normalizedRegisterName(_ rawName: String) -> String {
    rawName
        .replacingOccurrences(of: "%s", with: "")
        .trimmingCharacters(in: CharacterSet(charactersIn: "_"))
}

private func gpioRegisterVariableName(for register: SVDRegister, elementIndex: Int? = nil) -> String? {
    switch normalizedRegisterName(register.name) {
    case "DIR":
        return "dataDirection"
    case "DIRCLR":
        return "dataDirectionClear"
    case "DIRSET":
        return "dataDirectionSet"
    case "DIRTGL":
        return "dataDirectionToggle"
    case "OUT":
        return "dataRegister"
    case "OUTCLR":
        return "dataRegisterClear"
    case "OUTSET":
        return "dataRegisterSet"
    case "OUTTGL":
        return "dataOutputValueToggle"
    case "IN":
        return "inputAddress"
    case "CTRL":
        return "inputSamplingMode"
    case "WRCONFIG":
        return "writeConfiguration"
    case "PMUX0":
        guard let elementIndex else {
            return nil
        }

        return "peripheralMultiplexing\(elementIndex)"
    case "PINCFG0":
        guard let elementIndex else {
            return nil
        }

        return "pinConfiguration\(elementIndex)"
    default:
        return nil
    }
}
