//
//  PowerManager.swift
//  SwiftARMGeneratorCLI
//
//  Created by HALGEN on 05/11/2026.
//

import Foundation

struct PowerManagerGenerator: PeripheralGenerator {
    let name = "PowerManager"
    let subdirectory = "module"

    func supports(device: SVDDevice) -> Bool {
        pmPeripheral(in: device) != nil
    }

    func generate(device: SVDDevice) -> [GeneratedCodeFile] {
        guard let peripheral = pmPeripheral(in: device) else {
            return []
        }

        return [buildPowerManagerFile(device: device, peripheral: peripheral, documentation: nil)]
    }

    func generate(device: SVDDevice, documentation: ChipDocumentationLoader) -> [GeneratedCodeFile] {
        guard let peripheral = pmPeripheral(in: device) else {
            return []
        }

        return [buildPowerManagerFile(device: device, peripheral: peripheral, documentation: documentation)]
    }
}

// MARK: - Peripheral Detection

private func pmPeripheral(in device: SVDDevice) -> SVDPeripheral? {
    device.peripherals.first { $0.name == "PM" || $0.groupName == "PM" }
}

// MARK: - File Builder

private func buildPowerManagerFile(
    device: SVDDevice,
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?
) -> GeneratedCodeFile {
    let fileName = "PowerManager.swift"
    let moduleName = device.generatedSwiftModuleName
    let baseName = "PM_BASE"
    let baseAddress = peripheral.baseAddress ?? 0

    var code = generatedFileHeader(
        fileName: fileName,
        moduleName: moduleName,
        description: "Generated by Swift ARM Generator from \(device.name)."
    )

    code += "@usableFromInline let \(baseName): UInt = \(hexLiteral(baseAddress, minimumDigits: 8))   // SAMD21 datasheet Section 16.8\n\n"

    code += """
    /// Power Manager
    ///
    /// Controls sleep mode, CPU/APB clock prescalers, peripheral clock masks,
    /// clock-ready interrupts, and reset-cause flags.
    ///
    /// See SAMD21 datasheet Section 16.
    struct PowerManager {

    """

    code += generatePMEnums()

    for register in peripheral.registers {
        code += pmRegisterSectionHeader(for: register)
        code += generateSVDRegister(
            register: register,
            baseName: baseName,
            indentation: 4,
            writeBehavior: pmWriteBehavior(for: register),
            registerData: { register in
                pmRegisterData(for: register, peripheral: peripheral, documentation: documentation)
            },
            bitfieldData: { field in
                pmBitfieldData(for: field, register: register, peripheral: peripheral, documentation: documentation)
            }
        )
    }

    code += "}\n"

    return GeneratedCodeFile(fileName: fileName, content: code, subdirectory: "module")
}

// MARK: - Enum Generation

private func generatePMEnums() -> String {
    """
        // MARK: - Supporting Enums

        /// Idle sleep mode depth (SLEEP.IDLE).
        enum IdleMode: UInt32 {
            case cpu = 0
            case ahb = 1
            case apb = 2
        }

        /// Clock prescaler division for the CPU, APBA, APBB, and APBC buses.
        enum ClockDivider: UInt32 {
            case div1 = 0
            case div2 = 1
            case div4 = 2
            case div8 = 3
            case div16 = 4
            case div32 = 5
            case div64 = 6
            case div128 = 7
        }


    """
}

// MARK: - Register Generation Data

private func pmRegisterSectionHeader(for register: SVDRegister) -> String {
    let offset = register.addressOffset.map { hexLiteral($0) } ?? "unknown"
    let size = register.size ?? 32
    let description = register.description ?? "Register"

    return "    // MARK: - \(register.name) - \(description) (Offset \(offset), \(size)-bit)\n\n"
}

private func pmRegisterData(
    for register: SVDRegister,
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?
) -> SupplementalRegisterData {
    if let documentation {
        return documentation.supplementalData(for: register, peripheral: peripheral)
    }

    return SupplementalRegisterData(
        variableName: swiftMemberIdentifier(from: register.displayName ?? register.name),
        valueType: "UInt32",
        defaultValue: "",
        documentation: "",
        access: register.access ?? "read-write",
        isMissing: true
    )
}

private func pmBitfieldData(
    for field: SVDField,
    register: SVDRegister,
    peripheral: SVDPeripheral,
    documentation: ChipDocumentationLoader?
) -> SupplementalBitfieldData {
    if let documentation {
        return documentation.supplementalData(for: field, register: register, peripheral: peripheral)
    }

    return SupplementalBitfieldData(
        variableName: swiftMemberIdentifier(from: field.name),
        valueType: field.bitWidth == 1 ? "Bool" : "UInt32",
        defaultValue: "",
        documentation: "",
        access: pmAccess(from: field.access ?? register.access ?? "read-write"),
        isMissing: true
    )
}

private func pmWriteBehavior(for register: SVDRegister) -> SVDRegisterWriteBehavior {
    switch register.name {
    case "INTENCLR", "INTENSET", "INTFLAG":
        return .writeOneToClear
    default:
        return .normal
    }
}

private func pmAccess(from access: String) -> Access {
    switch access.lowercased() {
    case "read-only", "r":
        return .read
    case "write-only", "w":
        return .write
    default:
        return .readWrite
    }
}
