//
//  SERCOM.swift
//  SwiftARMGeneratorCLI
//
//  Created by HALGEN on 05/05/2026.
//

import Foundation

struct SERCOMGenerator: PeripheralGenerator {
    let name: String = "SERCOM"
    let subdirectory: String = "module/SERCOM"

    func supports(device: SVDDevice) -> Bool {
        sercomDefinition(in: device) != nil && sercomInstances(in: device).isEmpty == false
    }

    func generate(device: SVDDevice) -> [GeneratedCodeFile] {
        guard let definition = sercomDefinition(in: device) else {
            return []
        }

        let instances = sercomInstances(in: device)
        guard instances.isEmpty == false else {
            return []
        }

        var files = [
            buildSERCOMSupport(device: device, definition: definition, subdirectory: subdirectory)
        ]

        files.append(
            contentsOf: instances.map { instance in
                buildSERCOMInstance(device: device, definition: definition, instance: instance, subdirectory: subdirectory)
            }
        )

        return files
    }
}

private struct SERCOMInstance {
    let name: String
    let baseAddress: UInt64
}

private func buildSERCOMSupport(device: SVDDevice, definition: SVDPeripheral, subdirectory: String) -> GeneratedCodeFile {
    let fileName = "SERCOM.swift"
    let moduleName = device.generatedSwiftModuleName

    var code = generatedFileHeader(
        fileName: fileName,
        moduleName: moduleName,
        description: "Generated by Swift ARM Generator from \(device.name)."
    )

    code += """
    protocol SERCOMInstance {
        static var baseAddress: UInt { get }
    }

    struct SERCOM {
        private init() {}
    }

    struct SERCOMRegisterField {
        let offset: UInt32
        let width: UInt32

        var mask: UInt32 {
            guard width < 32 else {
                return UInt32.max
            }

            return ((UInt32(1) << width) - 1) << offset
        }

        @inline(__always)
        func read(from registerValue: UInt32) -> UInt32 {
            (registerValue & mask) >> offset
        }

        @inline(__always)
        func inserting(_ fieldValue: UInt32, into registerValue: UInt32) -> UInt32 {
            (registerValue & ~mask) | ((fieldValue << offset) & mask)
        }
    }

    """

    if definition.registers.isEmpty == false {
        code += buildSERCOMRegisterLayout(
            name: "SERCOMRegisters",
            description: definition.description ?? definition.name,
            registers: definition.registers,
            clusters: definition.clusters,
            baseOffset: 0
        )
    } else {
        for cluster in definition.clusters {
            code += buildSERCOMClusterLayout(cluster: cluster, typeName: sercomLayoutTypeName(for: cluster), baseOffset: 0)
        }
    }

    return GeneratedCodeFile(fileName: fileName, content: code, subdirectory: subdirectory)
}

private func buildSERCOMInstance(
    device: SVDDevice,
    definition: SVDPeripheral,
    instance: SERCOMInstance,
    subdirectory: String
) -> GeneratedCodeFile {
    let fileName = "\(instance.name).swift"
    let moduleName = device.generatedSwiftModuleName

    var code = generatedFileHeader(
        fileName: fileName,
        moduleName: moduleName,
        description: "Generated by Swift ARM Generator from \(device.name)."
    )

    code += """
    extension SERCOM {
        struct \(instance.name): SERCOMInstance {
            private init() {}
            static let baseAddress: UInt = \(hexLiteral(instance.baseAddress, minimumDigits: 8))

    """

    if definition.registers.isEmpty == false {
        code += "        typealias Registers = SERCOMRegisters<\(instance.name)>\n"
    }

    for cluster in definition.clusters {
        let clusterName = swiftTypeIdentifier(from: cleanedSVDName(cluster.name))
        code += "        typealias \(clusterName) = \(sercomLayoutTypeName(for: cluster))<\(instance.name)>\n"
    }

    code += """
        }
    }
    """

    return GeneratedCodeFile(fileName: fileName, content: code, subdirectory: subdirectory)
}

private func sercomDefinition(in device: SVDDevice) -> SVDPeripheral? {
    device.peripherals.first { peripheral in
        isSERCOMPeripheral(peripheral) && (peripheral.registers.isEmpty == false || peripheral.clusters.isEmpty == false)
    }
}

private func sercomInstances(in device: SVDDevice) -> [SERCOMInstance] {
    device.peripherals
        .filter(isSERCOMPeripheral)
        .compactMap { peripheral -> SERCOMInstance? in
            guard let baseAddress = peripheral.baseAddress else {
                return nil
            }

            return SERCOMInstance(name: peripheral.name, baseAddress: baseAddress)
        }
        .sorted { lhs, rhs in
            sercomInstanceIndex(lhs.name) < sercomInstanceIndex(rhs.name)
        }
}

private func isSERCOMPeripheral(_ peripheral: SVDPeripheral) -> Bool {
    isSERCOMInstanceName(peripheral.name)
        && (peripheral.groupName == "SERCOM" || peripheral.derivedFrom?.hasPrefix("SERCOM") == true || peripheral.clusters.isEmpty == false)
}

private func isSERCOMInstanceName(_ name: String) -> Bool {
    guard name.hasPrefix("SERCOM") else {
        return false
    }

    let suffix = name.dropFirst("SERCOM".count)
    return suffix.isEmpty == false && suffix.allSatisfy { $0.isNumber }
}

private func sercomInstanceIndex(_ name: String) -> Int {
    Int(name.dropFirst("SERCOM".count)) ?? 0
}

private func buildSERCOMClusterLayout(cluster: SVDCluster, typeName: String, baseOffset: UInt64) -> String {
    buildSERCOMRegisterLayout(
        name: typeName,
        description: cluster.description ?? cluster.name,
        registers: cluster.registers,
        clusters: cluster.clusters,
        baseOffset: baseOffset + (cluster.addressOffset ?? 0)
    )
}

private func buildSERCOMRegisterLayout(
    name: String,
    description: String,
    registers: [SVDRegister],
    clusters: [SVDCluster],
    baseOffset: UInt64
) -> String {
    var code = """
    /// \(description)
    struct \(name)<Instance: SERCOMInstance> {
        private init() {}

    """

    for register in registers {
        code += buildSERCOMRegister(register: register, baseOffset: baseOffset, indentation: 4)
    }

    for cluster in clusters {
        let clusterName = swiftTypeIdentifier(from: cleanedSVDName(cluster.name))
        let nestedTypeName = "\(name)\(clusterName)"

        code += "    typealias \(clusterName) = \(nestedTypeName)<Instance>\n\n"
        code += buildSERCOMClusterLayout(cluster: cluster, typeName: nestedTypeName, baseOffset: baseOffset)
    }

    code += """
    }

    """

    return code
}

private func buildSERCOMRegister(register: SVDRegister, baseOffset: UInt64, indentation: Int) -> String {
    if let dim = register.dim, dim > 1 {
        return (0..<dim)
            .map { elementIndex in
                buildSERCOMRegisterProperty(
                    register: register,
                    baseOffset: baseOffset,
                    elementIndex: elementIndex,
                    indentation: indentation
                )
            }
            .joined()
    }

    return buildSERCOMRegisterProperty(
        register: register,
        baseOffset: baseOffset,
        elementIndex: nil,
        indentation: indentation
    )
}

private func buildSERCOMRegisterProperty(
    register: SVDRegister,
    baseOffset: UInt64,
    elementIndex: Int?,
    indentation: Int
) -> String {
    guard let addressOffset = register.addressOffset else {
        return ""
    }

    let offset = baseOffset + addressOffset + UInt64(elementIndex ?? 0) * (register.dimIncrement ?? 0)
    let registerName = displaySVDName(register.name, elementIndex: elementIndex)
    let variableName = swiftMemberIdentifier(from: registerName)
    let addressExpression = sercomRegisterAddressExpression(baseName: "Instance.baseAddress", offset: offset)
    let isReadOnly = register.access == "read-only"
    let registerSize = register.size ?? 32
    let spaces = String(repeating: " ", count: indentation)
    let getter = sercomIndent(
        sercomBuildGetter(addressExpression: addressExpression, offset: offset, registerSize: registerSize),
        by: indentation + 4
    )
    let setter = isReadOnly ? "" : sercomIndent(
        sercomBuildSetter(addressExpression: addressExpression, offset: offset, registerSize: registerSize),
        by: indentation + 4
    )
    let bitfields = buildSERCOMBitfieldAccessors(
        register: register,
        registerName: registerName,
        parentVariableName: variableName,
        indentation: indentation
    )

    return """
    \(sercomIndent(makeSERCOMRegisterDocumentation(registerName: registerName, register: register), by: indentation))
    \(spaces)@inline(__always)
    \(spaces)static var \(variableName): UInt32 {
    \(getter)
    \(setter)
    \(spaces)}

    \(bitfields)
    """
}

private func sercomBuildGetter(addressExpression: String, offset: UInt64, registerSize: Int) -> String {
    switch registerSize {
    case 8:
        let alignedOffset = offset & ~0x3
        let shift = (offset & 0x3) * 8
        let alignedExpression = sercomRegisterAddressExpression(
            baseName: sercomAddressExpressionBase(addressExpression),
            offset: alignedOffset
        )

        return """
        get {
            (_volatileRegisterReadUInt32(\(alignedExpression)) >> \(shift)) & 0x000000FF
        }
        """
    case 16:
        let alignedOffset = offset & ~0x3
        let shift = (offset & 0x2) * 8
        let alignedExpression = sercomRegisterAddressExpression(
            baseName: sercomAddressExpressionBase(addressExpression),
            offset: alignedOffset
        )

        return """
        get {
            (_volatileRegisterReadUInt32(\(alignedExpression)) >> \(shift)) & 0x0000FFFF
        }
        """
    default:
        return """
        get {
            _volatileRegisterReadUInt32(\(addressExpression))
        }
        """
    }
}

private func sercomBuildSetter(addressExpression: String, offset: UInt64, registerSize: Int) -> String {
    switch registerSize {
    case 8:
        let alignedOffset = offset & ~0x3
        let shift = (offset & 0x3) * 8
        let mask = UInt64(0xFF) << shift
        let alignedExpression = sercomRegisterAddressExpression(
            baseName: sercomAddressExpressionBase(addressExpression),
            offset: alignedOffset
        )

        return """
        set {
            let word = _volatileRegisterReadUInt32(\(alignedExpression))
            _volatileRegisterWriteUInt32(\(alignedExpression), (word & \(hexLiteral(~mask & 0xFFFFFFFF, minimumDigits: 8))) | ((newValue & 0xFF) << \(shift)))
        }
        """
    case 16:
        let alignedOffset = offset & ~0x3
        let shift = (offset & 0x2) * 8
        let mask = UInt64(0xFFFF) << shift
        let alignedExpression = sercomRegisterAddressExpression(
            baseName: sercomAddressExpressionBase(addressExpression),
            offset: alignedOffset
        )

        return """
        set {
            let word = _volatileRegisterReadUInt32(\(alignedExpression))
            _volatileRegisterWriteUInt32(\(alignedExpression), (word & \(hexLiteral(~mask & 0xFFFFFFFF, minimumDigits: 8))) | ((newValue & 0xFFFF) << \(shift)))
        }
        """
    default:
        return """
        set {
            _volatileRegisterWriteUInt32(\(addressExpression), newValue)
        }
        """
    }
}

private func sercomRegisterAddressExpression(baseName: String, offset: UInt64) -> String {
    guard offset != 0 else {
        return baseName
    }

    return "\(baseName) + \(hexLiteral(offset))"
}

private func sercomAddressExpressionBase(_ addressExpression: String) -> String {
    String(addressExpression.split(separator: "+", maxSplits: 1).first ?? Substring(addressExpression))
        .trimmingCharacters(in: .whitespaces)
}

private func makeSERCOMRegisterDocumentation(registerName: String, register: SVDRegister) -> String {
    var lines = [
        "/// \(register.description ?? registerName) - \(registerName)"
    ]

    for field in register.fields {
        guard let fieldDescription = field.description else {
            continue
        }

        lines.append("/// \(field.name): \(fieldDescription)")
    }

    return lines.joined(separator: "\n")
}

private func sercomIndent(_ text: String, by spaces: Int) -> String {
    let prefix = String(repeating: " ", count: spaces)

    return text
        .split(separator: "\n", omittingEmptySubsequences: false)
        .map { line in
            line.isEmpty ? "" : prefix + line
        }
        .joined(separator: "\n")
}

private func buildSERCOMBitfieldAccessors(
    register: SVDRegister,
    registerName: String,
    parentVariableName: String,
    indentation: Int
) -> String {
    guard register.fields.isEmpty == false else {
        return ""
    }

    let spaces = String(repeating: " ", count: indentation)
    var code = ""

    for field in register.fields {
        guard let bitOffset = field.bitOffset,
              let bitWidth = field.bitWidth else {
            continue
        }

        let accessorName = bitfieldAccessorName(
            registerVariableName: parentVariableName,
            fieldName: field.name
        )
        let fieldHelper = "SERCOMRegisterField(offset: \(bitOffset), width: \(bitWidth))"
        let setter = register.access == "read-only" || fieldAccessIsReadOnly(field.access) ? "" : """
    \(spaces)    set {
    \(spaces)        \(parentVariableName) = \(fieldHelper).inserting(newValue, into: \(parentVariableName))
    \(spaces)    }
    """

        code += """
    \(spaces)/// \(field.description ?? field.name) bitfield of \(registerName).
    \(spaces)@inline(__always)
    \(spaces)static var \(accessorName): UInt32 {
    \(spaces)    get {
    \(spaces)        \(fieldHelper).read(from: \(parentVariableName))
    \(spaces)    }
    \(setter)
    \(spaces)}

    """
    }

    return code
}

private func fieldAccessIsReadOnly(_ access: String?) -> Bool {
    access == "read-only"
}

private func displaySVDName(_ rawName: String, elementIndex: Int?) -> String {
    let elementName = elementIndex.map(String.init) ?? ""
    return cleanedSVDName(rawName.replacingOccurrences(of: "%s", with: elementName))
}

private func cleanedSVDName(_ rawName: String) -> String {
    rawName.trimmingCharacters(in: CharacterSet(charactersIn: "_"))
}

private func sercomLayoutTypeName(for cluster: SVDCluster) -> String {
    "SERCOM\(swiftTypeIdentifier(from: cleanedSVDName(cluster.name)))"
}

private func bitfieldAccessorName(registerVariableName: String, fieldName: String) -> String {
    let fieldVariableName = swiftMemberIdentifier(from: fieldName)
    guard fieldVariableName != registerVariableName else {
        return "\(registerVariableName)Value"
    }

    return "\(registerVariableName)\(upperCamelSuffix(fieldVariableName))"
}

private func upperCamelSuffix(_ rawValue: String) -> String {
    guard let first = rawValue.first else {
        return ""
    }

    return String(first).uppercased() + rawValue.dropFirst()
}

private func swiftMemberIdentifier(from rawValue: String) -> String {
    let identifier = swiftTypeIdentifier(from: cleanedSVDName(rawValue))
    let parts = identifier
        .split(separator: "_")
        .map(String.init)
        .filter { $0.isEmpty == false }

    guard let first = parts.first else {
        return "_"
    }

    let lowercasedFirst = first.lowercased()
    let tail = parts.dropFirst().map { part -> String in
        let lowercased = part.lowercased()
        guard let firstCharacter = lowercased.first else {
            return ""
        }

        return String(firstCharacter).uppercased() + lowercased.dropFirst()
    }

    let memberName = ([lowercasedFirst] + tail).joined()
    guard swiftReservedWords.contains(memberName) == false else {
        return "\(memberName)Value"
    }

    return memberName
}

private let swiftReservedWords: Set<String> = [
    "associatedtype",
    "class",
    "deinit",
    "enum",
    "extension",
    "fileprivate",
    "func",
    "import",
    "init",
    "inout",
    "internal",
    "let",
    "open",
    "operator",
    "private",
    "precedencegroup",
    "protocol",
    "public",
    "rethrows",
    "static",
    "struct",
    "subscript",
    "typealias",
    "var",
    "break",
    "case",
    "continue",
    "default",
    "defer",
    "do",
    "else",
    "fallthrough",
    "for",
    "guard",
    "if",
    "in",
    "repeat",
    "return",
    "switch",
    "where",
    "while",
    "as",
    "any",
    "catch",
    "false",
    "is",
    "nil",
    "super",
    "self",
    "Self",
    "throw",
    "throws",
    "true",
    "try"
]
