//
//  SERCOM.swift
//  SwiftARMGeneratorCLI
//
//  Created by HALGEN on 05/05/2026.
//

import Foundation

struct SERCOMGenerator: PeripheralGenerator {
    let name: String = "SERCOM"
    let subdirectory: String = "module/SERCOM"

    func supports(device: SVDDevice) -> Bool {
        guard let definition = sercomDefinition(in: device) else {
            return false
        }

        return sercomModules(in: definition).isEmpty == false && sercomInstances(in: device).isEmpty == false
    }

    func generate(device: SVDDevice) -> [GeneratedCodeFile] {
        guard let definition = sercomDefinition(in: device) else {
            return []
        }

        let modules = sercomModules(in: definition)
        let instances = sercomInstances(in: device)
        guard modules.isEmpty == false && instances.isEmpty == false else {
            return []
        }

        return instances.map { instance in
            buildSERCOMInstance(
                device: device,
                instance: instance,
                modules: modules,
                subdirectory: subdirectory
            )
        }
    }
}

private struct SERCOMInstance {
    let name: String
    let baseAddress: UInt64
}

private func buildSERCOMInstance(
    device: SVDDevice,
    instance: SERCOMInstance,
    modules: [SVDCluster],
    subdirectory: String
) -> GeneratedCodeFile {
    let fileName = "\(instance.name).swift"
    let moduleName = device.generatedSwiftModuleName
    let baseName = "\(instance.name)_BASE"

    var code = generatedFileHeader(
        fileName: fileName,
        moduleName: moduleName,
        description: "Generated by Swift ARM Generator from \(device.name)."
    )

    code += "@usableFromInline let \(baseName): UInt = \(hexLiteral(instance.baseAddress, minimumDigits: 8))\n\n"
    code += "/// \(instance.name) peripheral.\n"
    code += "struct \(instance.name) {\n\n"

    for module in modules {
        code += buildSERCOMModule(instanceName: instance.name, baseName: baseName, module: module)
    }

    code += "}\n"

    return GeneratedCodeFile(fileName: fileName, content: code, subdirectory: subdirectory)
}

private func sercomDefinition(in device: SVDDevice) -> SVDPeripheral? {
    device.peripherals.first { peripheral in
        isSERCOMPeripheral(peripheral) && peripheral.clusters.isEmpty == false
    }
}

private func sercomModules(in peripheral: SVDPeripheral) -> [SVDCluster] {
    let supportedModules: Set<String> = ["I2CM", "I2CS", "SPI", "USART"]

    return peripheral.clusters.filter { cluster in
        supportedModules.contains(cleanedSVDName(cluster.name))
    }
}

private func sercomInstances(in device: SVDDevice) -> [SERCOMInstance] {
    device.peripherals
        .filter(isSERCOMPeripheral)
        .compactMap { peripheral -> SERCOMInstance? in
            guard let baseAddress = peripheral.baseAddress else {
                return nil
            }

            return SERCOMInstance(name: peripheral.name, baseAddress: baseAddress)
        }
        .sorted { lhs, rhs in
            sercomInstanceIndex(lhs.name) < sercomInstanceIndex(rhs.name)
        }
}

private func isSERCOMPeripheral(_ peripheral: SVDPeripheral) -> Bool {
    isSERCOMInstanceName(peripheral.name)
        && (peripheral.groupName == "SERCOM" || peripheral.derivedFrom?.hasPrefix("SERCOM") == true || peripheral.clusters.isEmpty == false)
}

private func isSERCOMInstanceName(_ name: String) -> Bool {
    guard name.hasPrefix("SERCOM") else {
        return false
    }

    let suffix = name.dropFirst("SERCOM".count)
    return suffix.isEmpty == false && suffix.allSatisfy { $0.isNumber }
}

private func sercomInstanceIndex(_ name: String) -> Int {
    Int(name.dropFirst("SERCOM".count)) ?? 0
}

private func buildSERCOMModule(instanceName: String, baseName: String, module: SVDCluster) -> String {
    let moduleName = swiftTypeIdentifier(from: cleanedSVDName(module.name))
    let baseOffset = module.addressOffset ?? 0
    let registerVariableNames = sercomRegisterVariableNames(in: module.registers)
    let fieldUsage = sercomFieldUsage(in: module.registers)

    var code = ""
    code += sercomIndent("/// \(module.description ?? moduleName).", by: 4) + "\n"
    code += "    struct \(moduleName) {\n\n"

    for register in module.registers {
        code += buildSERCOMRegister(
            instanceName: instanceName,
            moduleName: moduleName,
            baseName: baseName,
            register: register,
            baseOffset: baseOffset,
            fieldUsage: fieldUsage,
            registerVariableNames: registerVariableNames,
            indentation: 8
        )
    }

    code += "    }\n\n"

    return code
}

private func buildSERCOMRegister(
    instanceName: String,
    moduleName: String,
    baseName: String,
    register: SVDRegister,
    baseOffset: UInt64,
    fieldUsage: [String: Int],
    registerVariableNames: Set<String>,
    indentation: Int
) -> String {
    if let dim = register.dim, dim > 1 {
        return (0..<dim)
            .map { elementIndex in
                buildSERCOMRegisterProperty(
                    instanceName: instanceName,
                    moduleName: moduleName,
                    baseName: baseName,
                    register: register,
                    baseOffset: baseOffset,
                    elementIndex: elementIndex,
                    fieldUsage: fieldUsage,
                    registerVariableNames: registerVariableNames,
                    indentation: indentation
                )
            }
            .joined()
    }

    return buildSERCOMRegisterProperty(
        instanceName: instanceName,
        moduleName: moduleName,
        baseName: baseName,
        register: register,
        baseOffset: baseOffset,
        elementIndex: nil,
        fieldUsage: fieldUsage,
        registerVariableNames: registerVariableNames,
        indentation: indentation
    )
}

private func buildSERCOMRegisterProperty(
    instanceName: String,
    moduleName: String,
    baseName: String,
    register: SVDRegister,
    baseOffset: UInt64,
    elementIndex: Int?,
    fieldUsage: [String: Int],
    registerVariableNames: Set<String>,
    indentation: Int
) -> String {
    guard let addressOffset = register.addressOffset else {
        return ""
    }

    let offset = baseOffset + addressOffset + UInt64(elementIndex ?? 0) * (register.dimIncrement ?? 0)
    let registerName = displaySVDName(register.name, elementIndex: elementIndex)
    let variableName = sercomRegisterVariableName(for: register)
    let addressExpression = sercomRegisterAddressExpression(baseName: baseName, offset: offset)
    let registerSize = register.size ?? 32
    let writeBehavior = sercomWriteBehavior(for: register)
    let isReadOnly = register.access == "read-only" && writeBehavior != .writeOneToClear
    let spaces = String(repeating: " ", count: indentation)
    let getter = sercomIndent(
        sercomBuildGetter(addressExpression: addressExpression, offset: offset, registerSize: registerSize),
        by: indentation + 4
    )
    let setter = isReadOnly ? "" : sercomIndent(
        sercomBuildSetter(
            addressExpression: addressExpression,
            offset: offset,
            registerSize: registerSize,
            writeBehavior: writeBehavior
        ),
        by: indentation + 4
    )
    let bitfields = buildSERCOMBitfieldAccessors(
        instanceName: instanceName,
        moduleName: moduleName,
        register: register,
        registerName: registerName,
        parentVariableName: variableName,
        parentExpression: "\(instanceName).\(moduleName).\(variableName)",
        baseName: baseName,
        baseOffset: offset,
        fieldUsage: fieldUsage,
        registerVariableNames: registerVariableNames,
        writeBehavior: writeBehavior,
        indentation: indentation
    )

    return """
    \(sercomIndent(makeSERCOMRegisterDocumentation(registerName: registerName, register: register), by: indentation))
    \(spaces)@inline(__always)
    \(spaces)static var \(variableName): UInt32 {
    \(getter)
    \(setter)
    \(spaces)}

    \(bitfields)
    """
}

private func sercomBuildGetter(addressExpression: String, offset: UInt64, registerSize: Int) -> String {
    buildSVDRegisterGetter(
        addressExpression: addressExpression,
        offset: offset,
        registerSize: registerSize
    )
}

private func sercomBuildSetter(
    addressExpression: String,
    offset: UInt64,
    registerSize: Int,
    writeBehavior: SVDRegisterWriteBehavior
) -> String {
    buildSVDRegisterSetter(
        addressExpression: addressExpression,
        offset: offset,
        registerSize: registerSize,
        writeBehavior: writeBehavior
    )
}

private func buildSERCOMBitfieldAccessors(
    instanceName: String,
    moduleName: String,
    register: SVDRegister,
    registerName: String,
    parentVariableName: String,
    parentExpression: String,
    baseName: String,
    baseOffset: UInt64,
    fieldUsage: [String: Int],
    registerVariableNames: Set<String>,
    writeBehavior: SVDRegisterWriteBehavior,
    indentation: Int
) -> String {
    guard register.fields.isEmpty == false else {
        return ""
    }

    let spaces = String(repeating: " ", count: indentation)
    var code = ""

    for field in register.fields {
        if register.fields.count == 1 && cleanedSVDName(field.name) == cleanedSVDName(register.name) {
            continue
        }

        guard let bitOffset = field.bitOffset,
              let bitWidth = field.bitWidth else {
            continue
        }

        let accessorName = bitfieldAccessorName(
            registerVariableName: parentVariableName,
            fieldName: field.name,
            fieldUsage: fieldUsage,
            registerVariableNames: registerVariableNames,
            registerName: register.name
        )
        let accessorType = svdBitfieldAccessorType(bitWidth: bitWidth)
        let getter = "get { \(svdBitfieldGetterExpression(parentExpression: parentExpression, bitOffset: bitOffset, bitWidth: bitWidth)) }"
        let setter = sercomBuildBitfieldSetter(
            field: field,
            bitOffset: bitOffset,
            bitWidth: bitWidth,
            parentExpression: parentExpression,
            registerAccess: register.access,
            writeBehavior: writeBehavior,
            baseName: baseName,
            baseOffset: baseOffset
        )

        code += """
        \(spaces)/// \(field.description ?? field.name)
        \(spaces)@inlinable @inline(__always)
        \(spaces)static var \(accessorName): \(accessorType) {
        \(spaces)    \(getter)
        \(setter.map { "\(spaces)    \($0)\n" } ?? "")\(spaces)}

        """
    }

    return code
}

private func sercomBuildBitfieldSetter(
    field: SVDField,
    bitOffset: Int,
    bitWidth: Int,
    parentExpression: String,
    registerAccess: String?,
    writeBehavior: SVDRegisterWriteBehavior,
    baseName: String,
    baseOffset: UInt64
) -> String? {
    if registerAccess == "read-only" && writeBehavior != .writeOneToClear {
        return nil
    }
    if fieldAccessIsReadOnly(field.access) && writeBehavior != .writeOneToClear {
        return nil
    }

    if writeBehavior == .writeOneToClear {
        return sercomBuildWriteOneToClearBitfieldSetter(
            baseName: baseName,
            baseOffset: baseOffset,
            fieldOffset: bitOffset,
            fieldWidth: bitWidth
        )
    }

    if bitWidth == 1 {
        return "set { \(parentExpression) = (\(parentExpression) & ~(UInt32(1) << \(bitOffset))) | (newValue ? UInt32(1) << \(bitOffset) : 0) }"
    }

    let mask = hexLiteral((UInt64(1) << UInt64(bitWidth)) - 1)
    return "set { \(parentExpression) = (\(parentExpression) & ~(UInt32(\(mask)) << \(bitOffset))) | ((newValue & \(mask)) << \(bitOffset)) }"
}

private func sercomBuildWriteOneToClearBitfieldSetter(
    baseName: String,
    baseOffset: UInt64,
    fieldOffset: Int,
    fieldWidth: Int
) -> String {
    let alignedOffset = baseOffset & ~0x3
    let registerShift = (baseOffset & 0x3) * 8
    let shift = UInt64(fieldOffset) + registerShift
    let addressExpression = sercomRegisterAddressExpression(baseName: baseName, offset: alignedOffset)

    if fieldWidth == 1 {
        return "set { if newValue { _volatileRegisterWriteUInt32(\(addressExpression), UInt32(1) << \(shift)) } }"
    }

    let fieldMask = hexLiteral(svdBitfieldMask(bitWidth: fieldWidth))
    let writeMask = hexLiteral(svdBitfieldMask(bitWidth: fieldWidth) << shift, minimumDigits: 8)
    return "set { if newValue != 0 { _volatileRegisterWriteUInt32(\(addressExpression), ((newValue & \(fieldMask)) << \(shift)) & \(writeMask)) } }"
}

private func sercomRegisterAddressExpression(baseName: String, offset: UInt64) -> String {
    svdRegisterAddressExpression(baseName: baseName, offset: offset)
}

private func sercomWriteBehavior(for register: SVDRegister) -> SVDRegisterWriteBehavior {
    switch cleanedSVDName(register.name) {
    case "INTFLAG", "STATUS":
        return .writeOneToClear
    default:
        return .normal
    }
}

private func makeSERCOMRegisterDocumentation(registerName: String, register: SVDRegister) -> String {
    var lines = [
        "/// \(register.description ?? registerName) - \(registerName)"
    ]

    for field in register.fields {
        guard let fieldDescription = field.description else {
            continue
        }

        lines.append("/// \(field.name): \(fieldDescription)")
    }

    return lines.joined(separator: "\n")
}

private func sercomIndent(_ text: String, by spaces: Int) -> String {
    svdIndent(text, by: spaces)
}

private func fieldAccessIsReadOnly(_ access: String?) -> Bool {
    access == "read-only"
}

private func displaySVDName(_ rawName: String, elementIndex: Int?) -> String {
    let elementName = elementIndex.map(String.init) ?? ""
    return cleanedSVDName(rawName.replacingOccurrences(of: "%s", with: elementName))
}

private func cleanedSVDName(_ rawName: String) -> String {
    rawName.trimmingCharacters(in: CharacterSet(charactersIn: "_"))
}

private func sercomRegisterVariableName(for register: SVDRegister) -> String {
    let baseName = swiftMemberIdentifier(from: cleanedSVDName(register.name))
    let hasSelfNamedField = register.fields.count > 1 && register.fields.contains { field in
        cleanedSVDName(field.name) == cleanedSVDName(register.name)
    }

    return hasSelfNamedField ? "\(baseName)Register" : baseName
}

private func sercomRegisterVariableNames(in registers: [SVDRegister]) -> Set<String> {
    Set(registers.compactMap { register in
        register.addressOffset.map { _ in
            sercomRegisterVariableName(for: register)
        }
    })
}

private func sercomFieldUsage(in registers: [SVDRegister]) -> [String: Int] {
    registers.reduce(into: [:]) { counts, register in
        for field in register.fields {
            counts[cleanedSVDName(field.name), default: 0] += 1
        }
    }
}

private func bitfieldAccessorName(
    registerVariableName: String,
    fieldName: String,
    fieldUsage: [String: Int],
    registerVariableNames: Set<String>,
    registerName: String
) -> String {
    let cleanedFieldName = cleanedSVDName(fieldName)
    let fieldVariableName = swiftMemberIdentifier(from: cleanedFieldName)
    let cleanedRegisterName = cleanedSVDName(registerName)

    if cleanedRegisterName == "CTRLA" && (cleanedFieldName == "SWRST" || cleanedFieldName == "ENABLE") {
        return fieldVariableName
    }

    let needsRegisterPrefix = (fieldUsage[cleanedFieldName] ?? 0) > 1
        || fieldVariableName == registerVariableName
        || registerVariableNames.contains(fieldVariableName)

    guard needsRegisterPrefix else {
        return fieldVariableName
    }

    return "\(registerVariableName)\(swiftUpperCamelIdentifier(from: cleanedFieldName))"
}

private func swiftMemberIdentifier(from rawValue: String) -> String {
    let identifier = swiftTypeIdentifier(from: cleanedSVDName(rawValue))
    let parts = identifier
        .split(separator: "_")
        .map(String.init)
        .filter { $0.isEmpty == false }

    guard let first = parts.first else {
        return "_"
    }

    let memberName = ([swiftLowerCamelIdentifier(from: first)] + parts.dropFirst().map(swiftUpperCamelIdentifier(from:))).joined()
    guard swiftReservedWords.contains(memberName) == false else {
        return "\(memberName)Value"
    }

    return memberName
}

private func swiftLowerCamelIdentifier(from rawValue: String) -> String {
    switch rawValue {
    case "RUNSTDBY":
        return "runStdby"
    default:
        return rawValue.lowercased()
    }
}

private func swiftUpperCamelIdentifier(from rawValue: String) -> String {
    let cleaned = cleanedSVDName(rawValue)
    if cleaned == "ENABLE" {
        return "Enable"
    }

    guard cleaned.contains("_") else {
        return cleaned
    }

    return cleaned
        .split(separator: "_")
        .map { part in
            let lowercased = part.lowercased()
            guard let first = lowercased.first else {
                return ""
            }

            return String(first).uppercased() + lowercased.dropFirst()
        }
        .joined()
}

private let swiftReservedWords: Set<String> = [
    "associatedtype",
    "class",
    "deinit",
    "enum",
    "extension",
    "fileprivate",
    "func",
    "import",
    "init",
    "inout",
    "internal",
    "let",
    "open",
    "operator",
    "private",
    "precedencegroup",
    "protocol",
    "public",
    "rethrows",
    "static",
    "struct",
    "subscript",
    "super",
    "typealias",
    "var",
    "break",
    "case",
    "continue",
    "default",
    "defer",
    "do",
    "else",
    "fallthrough",
    "for",
    "guard",
    "if",
    "in",
    "repeat",
    "return",
    "switch",
    "where",
    "while",
    "as",
    "any",
    "catch",
    "false",
    "is",
    "nil",
    "self",
    "Self",
    "throw",
    "throws",
    "true",
    "try"
]
